name: animapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  custom_switch: ^0.0.1
  lite_rolling_switch: ^0.1.1


  cupertino_icons: ^0.1.3
  intl: ^0.16.1 # Date formater
  font_awesome_flutter: ^8.2.0
  dio: ^1.0.13
  google_fonts: ^0.3.5
  google_maps_flutter: ^0.5.27+3
  responsive_builder: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  assets:
    - images/

  uses-material-design: true
